// Generates Figma Plugin API JavaScript that can be sent verbatim to
// `use_figma`. The whole point is to remove agent discretion: instead of
// asking the agent to translate inspect output into use_figma calls (which
// it keeps screwing up by skipping bindings), we emit the exact plugin code
// here and the agent's only job is to pipe each script through use_figma.
//
// The scripts are designed to be idempotent (re-runs don't duplicate) and
// self-resolving (each component script looks up variables by name at
// runtime, so they can reference variables a previous script created
// without us having to thread IDs through the JSON output).

import type { TokenCollection, TokenValue } from "./tokens.js";
import type { FigmaVariantProperty } from "./mapper.js";
import type { InspectionResult, ResolvedStyling, Bindings, RenderedChild } from "./inspect.js";

export interface PushScript {
  label: string;
  code: string;
}

export interface PushPlan {
  fileKey: string;
  scripts: PushScript[];
  warnings: string[];
}

// Figma color: { r, g, b } in 0..1, plus optional `a`.
interface RGB {
  r: number;
  g: number;
  b: number;
  a?: number;
}

// --- Variable-collection script ---

// Generates a one-time setup script that runs before variables + components.
// Does the housekeeping a designer would otherwise do by hand on a fresh file:
//   1. Create or refresh a "Cover" page at position 0 with the project name,
//      sync timestamp, and a brief contents table (page → component count).
//   2. Remove Figma's default "Page 1" if it's empty and there's other content
//      — keeps untitled files from carrying a useless first page after a sync.
export function generateSetupScript(input: {
  pageSummary: { name: string; componentCount: number }[];
  componentTotal: number;
  variableTotal: number;
}): PushScript {
  const ts = new Date().toISOString().slice(0, 10);
  const summary = input.pageSummary
    .map((p) => `${p.name} · ${p.componentCount} ${p.componentCount === 1 ? "component" : "components"}`);
  const lines: string[] = [];
  lines.push("// Auto-generated by storysync push — file-level setup.");
  lines.push("(async () => {");
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Regular" });`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });`);
  lines.push("");
  lines.push(`  // 1) Find or create the Cover page and pin it to position 0.`);
  lines.push(`  let cover = figma.root.children.find((p) => p.name === "Cover");`);
  lines.push(`  if (!cover) { cover = figma.createPage(); cover.name = "Cover"; }`);
  lines.push(`  if (figma.root.children.indexOf(cover) !== 0) figma.root.insertChild(0, cover);`);
  lines.push(`  await figma.setCurrentPageAsync(cover);`);
  lines.push(`  // Clear any previous sync's cover content so re-runs don't stack frames.`);
  lines.push(`  for (const child of [...cover.children]) child.remove();`);
  lines.push("");
  lines.push(`  // 2) Build the cover frame.`);
  lines.push(`  const frame = figma.createFrame();`);
  lines.push(`  frame.name = "Design system overview";`);
  lines.push(`  frame.layoutMode = "VERTICAL";`);
  lines.push(`  frame.primaryAxisSizingMode = "AUTO";`);
  lines.push(`  frame.counterAxisSizingMode = "AUTO";`);
  lines.push(`  frame.paddingTop = 64; frame.paddingRight = 64; frame.paddingBottom = 64; frame.paddingLeft = 64;`);
  lines.push(`  frame.itemSpacing = 16;`);
  lines.push(`  frame.fills = [];`);
  lines.push(`  cover.appendChild(frame);`);
  lines.push("");
  lines.push(`  const title = figma.createText();`);
  lines.push(`  title.fontName = { family: "Inter", style: "Semi Bold" };`);
  lines.push(`  title.fontSize = 48;`);
  lines.push(`  title.characters = "Design System";`);
  lines.push(`  frame.appendChild(title);`);
  lines.push("");
  lines.push(`  const subtitle = figma.createText();`);
  lines.push(`  subtitle.fontName = { family: "Inter", style: "Regular" };`);
  lines.push(`  subtitle.fontSize = 16;`);
  lines.push(`  subtitle.fills = [{ type: "SOLID", color: { r: 0.42, g: 0.45, b: 0.5 } }];`);
  lines.push(`  subtitle.characters = ${JSON.stringify(`Synced from Storybook via storysync · ${ts} · ${input.componentTotal} components · ${input.variableTotal} variables`)};`);
  lines.push(`  frame.appendChild(subtitle);`);
  lines.push("");
  if (summary.length) {
    lines.push(`  // Contents — one row per page (excluding Cover).`);
    lines.push(`  const spacer = figma.createFrame();`);
    lines.push(`  spacer.name = "spacer";`);
    lines.push(`  spacer.layoutMode = "VERTICAL";`);
    lines.push(`  spacer.primaryAxisSizingMode = "FIXED";`);
    lines.push(`  spacer.resize(1, 24);`);
    lines.push(`  spacer.fills = [];`);
    lines.push(`  frame.appendChild(spacer);`);
    for (const row of summary) {
      lines.push(`  { const t = figma.createText(); t.fontName = { family: "Inter", style: "Regular" }; t.fontSize = 14; t.characters = ${JSON.stringify(row)}; frame.appendChild(t); }`);
    }
  }
  lines.push("");
  lines.push(`  // 3) Remove an empty default "Page 1" if it's still hanging around.`);
  lines.push(`  const defaultPage = figma.root.children.find((p) => p.name === "Page 1" && p.children.length === 0);`);
  lines.push(`  if (defaultPage && figma.root.children.length > 1) defaultPage.remove();`);
  lines.push(`})();`);

  return {
    label: `Set up Cover page and clean default pages`,
    code: lines.join("\n"),
  };
}

export function generateVariablesScript(collections: TokenCollection[]): PushScript {
  const lines: string[] = [];
  lines.push("// Auto-generated by storysync push — creates/updates token variable collections.");
  lines.push("// Idempotent: re-running keeps existing variables and updates their values.");
  lines.push("(async () => {");
  lines.push("  const upsertCollection = (name) => {");
  lines.push("    let c = figma.variables.getLocalVariableCollections().find((c) => c.name === name);");
  lines.push("    if (!c) c = figma.variables.createVariableCollection(name);");
  lines.push("    return c;");
  lines.push("  };");
  lines.push("  const upsertVariable = (collection, name, type) => {");
  lines.push("    const existing = figma.variables");
  lines.push("      .getLocalVariables()");
  lines.push("      .find((v) => v.variableCollectionId === collection.id && v.name === name);");
  lines.push("    return existing || figma.variables.createVariable(name, collection, type);");
  lines.push("  };");
  lines.push("");

  let total = 0;
  for (const coll of collections) {
    const meta = COLLECTION_META[coll.category];
    if (!meta) continue;

    const safeName = meta.name;
    const figmaType = meta.figmaType;
    const scopes = JSON.stringify(meta.scopes);

    lines.push(`  // ${safeName} (${coll.tokens.length} variables)`);
    lines.push(`  {`);
    lines.push(`    const coll = upsertCollection(${JSON.stringify(safeName)});`);
    lines.push(`    const mode = coll.modes[0].modeId;`);

    for (const t of coll.tokens) {
      const value = serializeTokenValue(coll.category, t);
      if (value == null) continue;
      lines.push(`    {`);
      lines.push(`      const v = upsertVariable(coll, ${JSON.stringify(t.name)}, ${JSON.stringify(figmaType)});`);
      lines.push(`      v.setValueForMode(mode, ${value});`);
      lines.push(`      v.scopes = ${scopes};`);
      lines.push(`    }`);
      total++;
    }
    lines.push(`  }`);
    lines.push("");
  }

  lines.push(`  console.log("storysync: upserted " + ${total} + " variables across ${collections.length} collections");`);
  lines.push("})();");

  return {
    label: `Create or update ${total} variables across ${collections.length} collections`,
    code: lines.join("\n"),
  };
}

interface CollectionMeta {
  name: string;
  figmaType: "COLOR" | "FLOAT" | "STRING";
  scopes: string[];
}

const COLLECTION_META: Record<string, CollectionMeta> = {
  colors: { name: "Colors", figmaType: "COLOR", scopes: ["ALL_FILLS", "STROKE_COLOR"] },
  spacing: { name: "Spacing", figmaType: "FLOAT", scopes: ["GAP", "WIDTH_HEIGHT"] },
  radius: { name: "Radius", figmaType: "FLOAT", scopes: ["CORNER_RADIUS"] },
  shadows: { name: "Shadows", figmaType: "STRING", scopes: ["ALL_SCOPES"] },
  typography: { name: "Typography", figmaType: "FLOAT", scopes: ["FONT_SIZE"] },
};

// Returns a JS literal expression for the value, or null when not serializable.
function serializeTokenValue(category: string, token: TokenValue): string | null {
  if (category === "colors") {
    const rgb = parseColorToRgb(token.value);
    if (!rgb) return null;
    return rgbToJsLiteral(rgb);
  }
  // Numeric categories: spacing / radius / typography.
  if (category === "spacing" || category === "radius" || category === "typography") {
    const px = lengthToPx(token.value);
    if (px == null) return null;
    return String(px);
  }
  // Shadows are stored as STRING for now (no first-class effect-style binding).
  if (category === "shadows") return JSON.stringify(token.value);
  return null;
}

// --- Component-set script ---

export interface ComponentInput {
  name: string;
  category?: string;
  variantProperties: FigmaVariantProperty[];
  styling: InspectionResult;
}

export function generateComponentScript(input: ComponentInput): PushScript {
  const pageName = sanitizeIdentifier(input.category || "Components", "category");
  const compName = sanitizeIdentifier(input.name, "component name");
  for (const p of input.variantProperties) {
    sanitizeIdentifier(p.name, "variant property name");
    for (const v of p.values) sanitizeIdentifier(v, "variant value");
  }
  const matrix = enumerateVariantMatrix(input.variantProperties);

  const lines: string[] = [];
  lines.push(`// Auto-generated by storysync push — ${compName} (${matrix.length} variants)`);
  lines.push(`(async () => {`);
  lines.push(`  // 1) Page lookup/create`);
  lines.push(`  let page = figma.root.children.find((p) => p.name === ${JSON.stringify(pageName)});`);
  lines.push(`  if (!page) { page = figma.createPage(); page.name = ${JSON.stringify(pageName)}; }`);
  lines.push(`  await figma.setCurrentPageAsync(page);`);
  lines.push("");

  lines.push(`  // 2) Variable lookup helper — resolves bindings at runtime`);
  lines.push(`  const lookupVar = (collName, varName) => {`);
  lines.push(`    const coll = figma.variables.getLocalVariableCollections().find((c) => c.name === collName);`);
  lines.push(`    if (!coll) return null;`);
  lines.push(`    return figma.variables.getLocalVariables().find((v) => v.variableCollectionId === coll.id && v.name === varName) || null;`);
  lines.push(`  };`);
  lines.push("");
  // Recursive child builder. Created once per script and re-used for
  // every nested frame/text inside a variant. The recursion bottoms out
  // when a child has no inner kids — either as a text leaf (`d.t`) or
  // an empty frame.
  lines.push(`  // 2b) Recursive child node builder — used by variants that captured`);
  lines.push(`  //     a DOM tree (wrapper components like Card with CardHeader/Content).`);
  lines.push(`  const buildChild = (d) => {`);
  lines.push(`    if (d.t != null) {`);
  lines.push(`      const lb = figma.createText();`);
  lines.push(`      lb.fontName = { family: d.tff || "Inter", style: d.tfs || "Regular" };`);
  lines.push(`      if (d.tfz != null) lb.fontSize = d.tfz;`);
  lines.push(`      lb.characters = d.t;`);
  lines.push(`      let lfp = null;`);
  lines.push(`      if (d.tf) lfp = { type: "SOLID", color: { r: d.tf[0], g: d.tf[1], b: d.tf[2] } };`);
  lines.push(`      if (d.tfb && lfp) { const v = lookupVar(d.tfb[0], d.tfb[1]); if (v) lfp = figma.variables.setBoundVariableForPaint(lfp, "color", v); }`);
  lines.push(`      if (lfp) lb.fills = [lfp];`);
  lines.push(`      return lb;`);
  lines.push(`    }`);
  lines.push(`    const f = figma.createFrame();`);
  lines.push(`    f.layoutMode = d.lm || "HORIZONTAL";`);
  lines.push(`    f.primaryAxisSizingMode = "AUTO";`);
  lines.push(`    f.counterAxisSizingMode = "AUTO";`);
  lines.push(`    if (d.pt != null) f.paddingTop = d.pt;`);
  lines.push(`    if (d.pr != null) f.paddingRight = d.pr;`);
  lines.push(`    if (d.pb != null) f.paddingBottom = d.pb;`);
  lines.push(`    if (d.pl != null) f.paddingLeft = d.pl;`);
  lines.push(`    if (d.is != null) f.itemSpacing = d.is;`);
  lines.push(`    if (d.isb) { const v = lookupVar(d.isb[0], d.isb[1]); if (v) f.setBoundVariable("itemSpacing", v); }`);
  lines.push(`    if (d.ai) f.counterAxisAlignItems = d.ai;`);
  lines.push(`    if (d.aj) f.primaryAxisAlignItems = d.aj;`);
  lines.push(`    if (d.cr != null) f.cornerRadius = d.cr;`);
  lines.push(`    if (d.crb) { const v = lookupVar(d.crb[0], d.crb[1]); if (v) { f.setBoundVariable("topLeftRadius", v); f.setBoundVariable("topRightRadius", v); f.setBoundVariable("bottomLeftRadius", v); f.setBoundVariable("bottomRightRadius", v); } }`);
  lines.push(`    let fp = null;`);
  lines.push(`    if (d.f) { fp = { type: "SOLID", color: { r: d.f[0], g: d.f[1], b: d.f[2] } }; if (d.f[3] != null) fp.opacity = d.f[3]; }`);
  lines.push(`    if (d.fb && fp) { const v = lookupVar(d.fb[0], d.fb[1]); if (v) fp = figma.variables.setBoundVariableForPaint(fp, "color", v); }`);
  lines.push(`    f.fills = fp ? [fp] : [];`);
  lines.push(`    let sp = null;`);
  lines.push(`    if (d.s) { sp = { type: "SOLID", color: { r: d.s[0], g: d.s[1], b: d.s[2] } }; if (d.s[3] != null) sp.opacity = d.s[3]; }`);
  lines.push(`    if (d.sb && sp) { const v = lookupVar(d.sb[0], d.sb[1]); if (v) sp = figma.variables.setBoundVariableForPaint(sp, "color", v); }`);
  lines.push(`    if (sp) { f.strokes = [sp]; if (d.sw != null) f.strokeWeight = d.sw; if (d.sd) f.dashPattern = d.sd; }`);
  lines.push(`    if (d.ef) f.effects = d.ef;`);
  lines.push(`    if (d.op != null) f.opacity = d.op;`);
  lines.push(`    if (d.kids) for (const k of d.kids) f.appendChild(buildChild(k));`);
  lines.push(`    return f;`);
  lines.push(`  };`);
  lines.push("");

  lines.push(`  // 3) Font preload (the only font we use for V1 labels)`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Regular" });`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Medium" });`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });`);
  lines.push("");

  lines.push(`  // 4) Remove any prior component set with the same name on this page so re-runs don't pile up`);
  lines.push(`  for (const child of page.children) {`);
  lines.push(`    if ((child.type === "COMPONENT_SET" || child.type === "COMPONENT") && child.name === ${JSON.stringify(compName)}) child.remove();`);
  lines.push(`  }`);
  lines.push("");

  // Build a compact payload per variant. We emit JSON + one apply-loop
  // instead of inlining each variant's setup so the script size scales
  // linearly with variant count (Catalyst Button at 92 variants used to
  // blow past use_figma's 50 000-char code limit when inlined).
  const payloads: VariantPayload[] = matrix.map((combo) => {
    const styling = mergeStylingForCombo(input.styling, combo);
    const bindings = mergeBindingsForCombo(input.styling, combo);
    const comboKey = formatVariantName(combo);
    // Render captured a real innerText for this combo (e.g. the story's
    // `children: "Label"` arg) — use that for the placeholder instead of
    // the component name, so a Catalyst Badge says "Label" not "Badge".
    const labelText = input.styling.renderedLabels?.[comboKey] ?? compName;
    const payload = buildVariantPayload(comboKey, labelText, styling, bindings);
    // Wrapper components (Card → CardHeader + Content) emit each child as
    // its own frame inside the variant, so the rendered structure shows
    // up in Figma instead of collapsing to a single styled box.
    const kids = input.styling.renderedChildren?.[comboKey];
    if (kids && kids.length) {
      payload.kids = kids.map((k) => buildChildPayload(k));
    }
    return payload;
  });

  lines.push(`  // 5) Variant payloads. Each entry is a compact descriptor of one`);
  lines.push(`  // component variant — the loop below applies them uniformly.`);
  lines.push(`  const VARIANTS = ${JSON.stringify(payloads)};`);
  lines.push("");
  lines.push(...APPLY_LOOP);
  lines.push("");

  if (matrix.length > 1) {
    lines.push(`  // 6) Combine into a component set.`);
    lines.push(`  const target = figma.combineAsVariants(variants, page);`);
    lines.push(`  target.name = ${JSON.stringify(compName)};`);
  } else {
    lines.push(`  // 6) Single-variant: append the lone component directly.`);
    lines.push(`  page.appendChild(variants[0]);`);
    lines.push(`  const target = variants[0];`);
  }

  // 7) Position the new component below anything already on the page so
  // re-running storysync push doesn't pile components on top of each other
  // at (0, 0). A simple vertical layout with 40px gap is enough for V1.
  lines.push("");
  lines.push(`  const peers = page.children.filter((c) => c !== target && (c.type === "COMPONENT" || c.type === "COMPONENT_SET"));`);
  lines.push(`  const bottom = peers.length ? Math.max(...peers.map((c) => c.y + c.height)) : 0;`);
  lines.push(`  target.x = 0;`);
  lines.push(`  target.y = peers.length ? bottom + 40 : 0;`);
  lines.push("");
  lines.push(`  console.log("storysync: created ${compName} with ${matrix.length} variants on page ${pageName}");`);
  lines.push(`})();`);

  return {
    label: `Create ${compName} (${matrix.length} variants) on ${pageName}`,
    code: lines.join("\n"),
  };
}

// Compact per-variant payload. Short keys keep the generated JSON small
// enough for many-variant components (Catalyst Button: 92) to fit under
// use_figma's 50KB code limit.
interface VariantPayload {
  n: string;                          // name
  lm?: "HORIZONTAL" | "VERTICAL";     // layout mode
  pt?: number; pr?: number; pb?: number; pl?: number;  // padding
  is?: number;                        // itemSpacing
  isb?: [string, string];             // itemSpacing binding [collection, token]
  ai?: string;                        // counterAxisAlignItems
  aj?: string;                        // primaryAxisAlignItems
  cr?: number;                        // cornerRadius
  crb?: [string, string];             // cornerRadius binding
  f?: [number, number, number, number?];   // fill [r,g,b,a?]
  fb?: [string, string];              // fill binding
  s?: [number, number, number, number?];   // stroke [r,g,b,a?]
  sw?: number;                        // strokeWeight
  sd?: number[];                      // dashPattern
  sb?: [string, string];              // stroke binding
  ef?: object[];                      // effects
  op?: number;                        // opacity
  // Label (used only when `kids` is absent)
  lt?: string;                        // label text
  lff?: string;                       // label font family
  lfs?: string;                       // label font style
  lfz?: number;                       // label font size
  lf?: [number, number, number];      // label fill
  lfb?: [string, string];             // label fill binding
  // Child frames captured from the rendered DOM. When present, the apply
  // loop builds these instead of stamping a single text label, so wrapper
  // components (Card → CardHeader + CardContent + CardFooter) render with
  // their actual structure visible.
  kids?: ChildPayload[];
}

// Child node — either a frame with its own layout + styling, or a text
// leaf identified by the `t` field. Recursively contains its own kids.
interface ChildPayload {
  // Container fields (mirror VariantPayload's layout/styling subset)
  lm?: "HORIZONTAL" | "VERTICAL";
  pt?: number; pr?: number; pb?: number; pl?: number;
  is?: number;
  isb?: [string, string];
  ai?: string;
  aj?: string;
  cr?: number;
  crb?: [string, string];
  f?: [number, number, number, number?];
  fb?: [string, string];
  s?: [number, number, number, number?];
  sw?: number;
  sd?: number[];
  sb?: [string, string];
  ef?: object[];
  op?: number;
  // Text-leaf fields
  t?: string;                         // text content; presence ⇒ leaf
  tff?: string;                       // text font family
  tfs?: string;                       // text font style
  tfz?: number;                       // text font size
  tf?: [number, number, number];      // text fill
  tfb?: [string, string];             // text fill binding
  // Recursive
  kids?: ChildPayload[];
}

// JS code that consumes a `VARIANTS` array of payloads and produces a
// `variants` array of Figma Components, in order. Kept as a static block
// so the emitter doesn't repeat it per script — it's the same logic for
// every component the user pushes.
const APPLY_LOOP: string[] = [
  `  const variants = [];`,
  `  for (const d of VARIANTS) {`,
  `    const c = figma.createComponent();`,
  `    c.name = d.n;`,
  `    if (d.lm) c.layoutMode = d.lm;`,
  `    c.primaryAxisSizingMode = "AUTO";`,
  `    c.counterAxisSizingMode = "AUTO";`,
  `    if (d.pt != null) c.paddingTop = d.pt;`,
  `    if (d.pr != null) c.paddingRight = d.pr;`,
  `    if (d.pb != null) c.paddingBottom = d.pb;`,
  `    if (d.pl != null) c.paddingLeft = d.pl;`,
  `    if (d.is != null) c.itemSpacing = d.is;`,
  `    if (d.isb) { const v = lookupVar(d.isb[0], d.isb[1]); if (v) c.setBoundVariable("itemSpacing", v); }`,
  `    if (d.ai) c.counterAxisAlignItems = d.ai;`,
  `    if (d.aj) c.primaryAxisAlignItems = d.aj;`,
  `    if (d.cr != null) c.cornerRadius = d.cr;`,
  `    if (d.crb) { const v = lookupVar(d.crb[0], d.crb[1]); if (v) { c.setBoundVariable("topLeftRadius", v); c.setBoundVariable("topRightRadius", v); c.setBoundVariable("bottomLeftRadius", v); c.setBoundVariable("bottomRightRadius", v); } }`,
  `    // Fill: build the paint, optionally bind its color to a variable.`,
  `    let fp = null;`,
  `    if (d.f) { fp = { type: "SOLID", color: { r: d.f[0], g: d.f[1], b: d.f[2] } }; if (d.f[3] != null) fp.opacity = d.f[3]; }`,
  `    if (d.fb && fp) { const v = lookupVar(d.fb[0], d.fb[1]); if (v) fp = figma.variables.setBoundVariableForPaint(fp, "color", v); }`,
  `    c.fills = fp ? [fp] : [];`,
  `    // Stroke (border).`,
  `    let sp = null;`,
  `    if (d.s) { sp = { type: "SOLID", color: { r: d.s[0], g: d.s[1], b: d.s[2] } }; if (d.s[3] != null) sp.opacity = d.s[3]; }`,
  `    if (d.sb && sp) { const v = lookupVar(d.sb[0], d.sb[1]); if (v) sp = figma.variables.setBoundVariableForPaint(sp, "color", v); }`,
  `    if (sp) { c.strokes = [sp]; if (d.sw != null) c.strokeWeight = d.sw; if (d.sd) c.dashPattern = d.sd; }`,
  `    if (d.ef) c.effects = d.ef;`,
  `    if (d.op != null) c.opacity = d.op;`,
  `    // Body: prefer captured child tree (wrapper components) over the`,
  `    // single text label. When neither is present the variant ends up as`,
  `    // a styled empty frame, which is fine — Figma autosizes it.`,
  `    if (d.kids && d.kids.length) {`,
  `      for (const k of d.kids) c.appendChild(buildChild(k));`,
  `    } else if (d.lt) {`,
  `      const lb = figma.createText();`,
  `      lb.fontName = { family: d.lff || "Inter", style: d.lfs || "Regular" };`,
  `      if (d.lfz != null) lb.fontSize = d.lfz;`,
  `      lb.characters = d.lt;`,
  `      let lfp = null;`,
  `      if (d.lf) lfp = { type: "SOLID", color: { r: d.lf[0], g: d.lf[1], b: d.lf[2] } };`,
  `      if (d.lfb && lfp) { const v = lookupVar(d.lfb[0], d.lfb[1]); if (v) lfp = figma.variables.setBoundVariableForPaint(lfp, "color", v); }`,
  `      if (lfp) lb.fills = [lfp];`,
  `      c.appendChild(lb);`,
  `    }`,
  `    variants.push(c);`,
  `  }`,
];

// Builds the compact payload for one variant from its merged styling +
// bindings. RGB tuples are rounded to 4 decimal places to keep JSON small
// while staying visually accurate.
function buildVariantPayload(
  name: string,
  labelText: string,
  styling: ResolvedStyling,
  bindings: Bindings,
): VariantPayload {
  const out: VariantPayload = { n: name };

  if (styling.layout) out.lm = styling.layout === "column" ? "VERTICAL" : "HORIZONTAL";
  else out.lm = "HORIZONTAL";

  const padding = parsePadding(styling.padding);
  out.pt = padding.t; out.pr = padding.r; out.pb = padding.b; out.pl = padding.l;

  const gapPx = parsePxNumber(styling.gap);
  if (gapPx != null) out.is = gapPx;
  if (bindings.gap) out.isb = [COLLECTION_META[bindings.gap.collection].name, bindings.gap.token];

  if (styling.alignItems) out.ai = figmaAlignment(styling.alignItems);
  if (styling.justifyContent) {
    const j = figmaJustify(styling.justifyContent);
    if (j) out.aj = j;
  }

  const radius = parsePxNumber(styling.borderRadius);
  if (radius != null) out.cr = radius;
  if (bindings.borderRadius) out.crb = [COLLECTION_META[bindings.borderRadius.collection].name, bindings.borderRadius.token];

  const fill = colorToTuple(styling.fill);
  if (fill) out.f = fill;
  if (bindings.fill) out.fb = [COLLECTION_META[bindings.fill.collection].name, bindings.fill.token];

  const strokeColor = styling.borderColor ?? extractBorderColor(styling.border);
  const stroke = colorToTuple(strokeColor);
  if (stroke) {
    out.s = stroke;
    out.sw = extractBorderWidth(styling.border) ?? 1;
    if (styling.borderStyle === "dashed") out.sd = [6, 4];
    else if (styling.borderStyle === "dotted") out.sd = [2, 2];
  }
  if (bindings.borderColor) out.sb = [COLLECTION_META[bindings.borderColor.collection].name, bindings.borderColor.token];

  const shadow = parseShadow(styling.shadow);
  if (shadow) out.ef = [shadow];

  if (styling.opacity != null) {
    const o = parseFloat(styling.opacity);
    if (!isNaN(o)) out.op = o;
  }

  // Label
  out.lt = labelText;
  out.lff = "Inter";
  out.lfs = pickFontStyle(styling);
  out.lfz = parsePxNumber(styling.fontSize) ?? 14;
  const labelFill = colorToTuple(styling.text);
  if (labelFill) out.lf = [labelFill[0], labelFill[1], labelFill[2]];
  if (bindings.text) out.lfb = [COLLECTION_META[bindings.text.collection].name, bindings.text.token];

  return out;
}

// Compact payload for one captured child node. The shape parallels
// VariantPayload's styling subset, but text content lives in `t` (with
// font fields prefixed `tf*`), and child kids recurse.
function buildChildPayload(child: RenderedChild): ChildPayload {
  const styling = child.styling;
  const bindings: Bindings = child.bindings ?? {};
  // Leaf: it's a text node with no children of its own.
  if (child.text && !child.children?.length) {
    const out: ChildPayload = {};
    out.t = child.text;
    out.tff = "Inter";
    out.tfs = pickFontStyle(styling);
    out.tfz = parsePxNumber(styling.fontSize) ?? 14;
    const tf = colorToTuple(styling.text);
    if (tf) out.tf = [tf[0], tf[1], tf[2]];
    if (bindings.text) out.tfb = [COLLECTION_META[bindings.text.collection].name, bindings.text.token];
    return out;
  }
  // Container.
  const out: ChildPayload = {};
  if (styling.layout) out.lm = styling.layout === "column" ? "VERTICAL" : "HORIZONTAL";
  else out.lm = "HORIZONTAL";
  const padding = parsePadding(styling.padding);
  if (padding.t || padding.r || padding.b || padding.l) {
    out.pt = padding.t; out.pr = padding.r; out.pb = padding.b; out.pl = padding.l;
  }
  const gapPx = parsePxNumber(styling.gap);
  if (gapPx != null) out.is = gapPx;
  if (bindings.gap) out.isb = [COLLECTION_META[bindings.gap.collection].name, bindings.gap.token];
  if (styling.alignItems) out.ai = figmaAlignment(styling.alignItems);
  if (styling.justifyContent) {
    const j = figmaJustify(styling.justifyContent);
    if (j) out.aj = j;
  }
  const radius = parsePxNumber(styling.borderRadius);
  if (radius != null) out.cr = radius;
  if (bindings.borderRadius) out.crb = [COLLECTION_META[bindings.borderRadius.collection].name, bindings.borderRadius.token];
  const fill = colorToTuple(styling.fill);
  if (fill) out.f = fill;
  if (bindings.fill) out.fb = [COLLECTION_META[bindings.fill.collection].name, bindings.fill.token];
  const strokeColor = styling.borderColor ?? extractBorderColor(styling.border);
  const stroke = colorToTuple(strokeColor);
  if (stroke) {
    out.s = stroke;
    out.sw = extractBorderWidth(styling.border) ?? 1;
    if (styling.borderStyle === "dashed") out.sd = [6, 4];
    else if (styling.borderStyle === "dotted") out.sd = [2, 2];
  }
  if (bindings.borderColor) out.sb = [COLLECTION_META[bindings.borderColor.collection].name, bindings.borderColor.token];
  const shadow = parseShadow(styling.shadow);
  if (shadow) out.ef = [shadow];
  if (styling.opacity != null) {
    const o = parseFloat(styling.opacity);
    if (!isNaN(o)) out.op = o;
  }
  // If the child has no grandchildren but does carry text, embed it as a
  // single text leaf so the frame isn't empty.
  if (child.text && !child.children?.length) {
    out.kids = [
      (() => {
        const leaf: ChildPayload = {};
        leaf.t = child.text;
        leaf.tff = "Inter";
        leaf.tfs = pickFontStyle(styling);
        leaf.tfz = parsePxNumber(styling.fontSize) ?? 14;
        const tf = colorToTuple(styling.text);
        if (tf) leaf.tf = [tf[0], tf[1], tf[2]];
        if (bindings.text) leaf.tfb = [COLLECTION_META[bindings.text.collection].name, bindings.text.token];
        return leaf;
      })(),
    ];
  } else if (child.children?.length) {
    out.kids = child.children.map((k) => buildChildPayload(k));
  }
  return out;
}

function colorToTuple(value: string | null | undefined): [number, number, number, number?] | null {
  if (!value || value === "transparent") return null;
  const rgb = parseColorToRgb(value);
  if (!rgb) return null;
  const r = Math.round(rgb.r * 10000) / 10000;
  const g = Math.round(rgb.g * 10000) / 10000;
  const b = Math.round(rgb.b * 10000) / 10000;
  if (rgb.a != null && rgb.a < 1) {
    return [r, g, b, Math.round(rgb.a * 10000) / 10000];
  }
  return [r, g, b];
}

// Cartesian product of variant properties. Each entry is a map of
// propName → value. For BOOLEAN, values are the strings "true"/"false".
function enumerateVariantMatrix(props: FigmaVariantProperty[]): Record<string, string>[] {
  if (!props.length) return [{}];
  let combos: Record<string, string>[] = [{}];
  for (const p of props) {
    const next: Record<string, string>[] = [];
    for (const existing of combos) {
      for (const v of p.values) next.push({ ...existing, [p.name]: v });
    }
    combos = next;
  }
  return combos;
}

function formatVariantName(combo: Record<string, string>): string {
  const parts = Object.entries(combo).map(([k, v]) => {
    // Figma reserves `/` as the variant group separator in component naming,
    // so values like Catalyst's `dark/zinc` or `dark/white` are rejected
    // when used inside a property value. Substitute with `-` so the variant
    // name parses cleanly. Reachable from code as `<Button color="dark/zinc">`
    // — the original prop value is untouched.
    return `${k}=${v.replace(/\//g, "-")}`;
  });
  return parts.length ? parts.join(", ") : "Default";
}

// For a given combo, walk the inspect result and merge base + the matching
// variant value's styling. Later values win over earlier so a variant value
// can override a base property.
// Merges base styling with the per-variant styling for a combo. When the
// combo doesn't specify a value for an axis the inspect spec defines (e.g.
// crenel's UI/Button doesn't enumerate `variant`/`size` via argTypes, so
// storysync map returns variantProperties = [] and the matrix collapses
// to a single {} combo), fall back to the axis's `defaultValue`. Without
// this, the synthesized single-variant component would only get base
// classes and miss the `variant === 'primary' && 'bg-blue-600 text-white'`
// styling entirely — which is what produced the bare-text-label rendering.
function mergeStylingForCombo(spec: InspectionResult, combo: Record<string, string>): ResolvedStyling {
  const out: ResolvedStyling = { ...spec.base };
  for (const variant of spec.variants) {
    const value = combo[variant.name] ?? variant.defaultValue;
    if (value == null) continue;
    const v = variant.values[value];
    if (!v) continue;
    Object.assign(out, v);
  }
  // Overlay runtime-rendered values on top. Only non-null fields win, so
  // the parser's structural info (layout, alignment) survives when render
  // doesn't supply it, while concrete values (fill, padding, dimensions)
  // come from what the browser actually painted.
  const rendered = spec.renderedStyling?.[formatVariantName(combo)];
  if (rendered) {
    for (const [k, v] of Object.entries(rendered)) {
      if (v != null) (out as Record<string, unknown>)[k] = v;
    }
  }
  return out;
}

function mergeBindingsForCombo(spec: InspectionResult, combo: Record<string, string>): Bindings {
  const out: Bindings = { ...spec.baseBindings };
  for (const variant of spec.variants) {
    const value = combo[variant.name] ?? variant.defaultValue;
    if (value == null) continue;
    const b = variant.bindings[value];
    if (!b) continue;
    Object.assign(out, b);
  }
  return out;
}

// --- Color / value parsers ---

export function parseColorToRgb(value: string): RGB | null {
  const v = value.trim();
  // Hex
  let m = v.match(/^#([0-9a-fA-F]{3,8})$/);
  if (m) {
    let hex = m[1];
    if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
    if (hex.length === 6 || hex.length === 8) {
      const r = parseInt(hex.slice(0, 2), 16) / 255;
      const g = parseInt(hex.slice(2, 4), 16) / 255;
      const b = parseInt(hex.slice(4, 6), 16) / 255;
      const a = hex.length === 8 ? parseInt(hex.slice(6, 8), 16) / 255 : undefined;
      return a != null ? { r, g, b, a } : { r, g, b };
    }
  }
  // rgb / rgba — accepts both Tailwind v3 space-separated form
  // (`rgb(255 0 0 / 0.5)`) and the legacy comma-separated form. Alpha may
  // be a fraction (`0.5`) or a percent (`50%`).
  m = v.match(/^rgba?\(\s*(\d+(?:\.\d+)?)\s*[,\s]\s*(\d+(?:\.\d+)?)\s*[,\s]\s*(\d+(?:\.\d+)?)\s*(?:[,\/]\s*(\d+(?:\.\d+)?%?))?\s*\)$/i);
  if (m) {
    const result: RGB = {
      r: parseFloat(m[1]) / 255,
      g: parseFloat(m[2]) / 255,
      b: parseFloat(m[3]) / 255,
    };
    if (m[4] != null) {
      const aStr = m[4];
      const a = aStr.endsWith("%") ? parseFloat(aStr) / 100 : parseFloat(aStr);
      if (!isNaN(a)) result.a = a;
    }
    return result;
  }
  // hsl / hsla — including the bare-component form `224 71% 4%` shadcn uses.
  m = v.match(/^hsla?\(\s*(\d+(?:\.\d+)?)(?:deg)?[,\s]+(\d+(?:\.\d+)?)%[,\s]+(\d+(?:\.\d+)?)%(?:[\s,/]+(\d*\.?\d+%?))?\s*\)$/i)
    ?? v.match(/^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%\s+(\d+(?:\.\d+)?)%$/);
  if (m) {
    const rgb = hslToRgb(parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3]));
    if (m[4] != null) {
      const aStr = m[4];
      const a = aStr.endsWith("%") ? parseFloat(aStr) / 100 : parseFloat(aStr);
      if (!isNaN(a)) return { ...rgb, a };
    }
    return rgb;
  }
  // oklab / oklch — Tailwind 4 emits colors in oklab space by default,
  // so `bg-zinc-900` resolves to e.g. `oklab(0.141 0.00136 -0.00481 / 0.9)`.
  // Convert via the standard sRGB transform (oklab → linear sRGB → sRGB).
  m = v.match(/^oklab\(\s*(-?\d*\.?\d+%?)\s+(-?\d*\.?\d+)\s+(-?\d*\.?\d+)(?:\s*\/\s*(-?\d*\.?\d+%?))?\s*\)$/i);
  if (m) {
    return oklabComponentsToRgb(parsePercentOrNumber(m[1], 1), parseFloat(m[2]), parseFloat(m[3]), m[4] != null ? parsePercentOrNumber(m[4], 1) : undefined);
  }
  m = v.match(/^oklch\(\s*(-?\d*\.?\d+%?)\s+(-?\d*\.?\d+%?)\s+(-?\d*\.?\d+)(?:deg)?(?:\s*\/\s*(-?\d*\.?\d+%?))?\s*\)$/i);
  if (m) {
    const L = parsePercentOrNumber(m[1], 1);
    const C = parsePercentOrNumber(m[2], 0.4); // oklch chroma is unitless, up to ~0.4
    const hDeg = parseFloat(m[3]);
    const h = (hDeg * Math.PI) / 180;
    const a = C * Math.cos(h);
    const b = C * Math.sin(h);
    return oklabComponentsToRgb(L, a, b, m[4] != null ? parsePercentOrNumber(m[4], 1) : undefined);
  }
  // Named special cases used by tokens
  if (v === "transparent") return { r: 0, g: 0, b: 0, a: 0 };
  if (v === "white") return { r: 1, g: 1, b: 1 };
  if (v === "black") return { r: 0, g: 0, b: 0 };
  return null;
}

function parsePercentOrNumber(s: string, scale: number): number {
  if (s.endsWith("%")) return (parseFloat(s) / 100) * scale;
  return parseFloat(s);
}

// oklab → sRGB (0..1). Reference: https://bottosson.github.io/posts/oklab/
function oklabComponentsToRgb(L: number, a: number, b: number, alpha?: number): RGB {
  // Step 1: oklab → linear RGB (LMS intermediate)
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const lCubed = l_ * l_ * l_;
  const mCubed = m_ * m_ * m_;
  const sCubed = s_ * s_ * s_;
  const rLin = 4.0767416621 * lCubed - 3.3077115913 * mCubed + 0.2309699292 * sCubed;
  const gLin = -1.2684380046 * lCubed + 2.6097574011 * mCubed - 0.3413193965 * sCubed;
  const bLin = -0.0041960863 * lCubed - 0.7034186147 * mCubed + 1.707614701 * sCubed;
  // Step 2: linear sRGB → gamma-corrected sRGB (0..1)
  const r = linearToSrgb(rLin);
  const g = linearToSrgb(gLin);
  const bComp = linearToSrgb(bLin);
  const result: RGB = { r: clamp01(r), g: clamp01(g), b: clamp01(bComp) };
  if (alpha != null && alpha < 1) result.a = clamp01(alpha);
  return result;
}

function linearToSrgb(v: number): number {
  if (v <= 0.0031308) return 12.92 * v;
  return 1.055 * Math.pow(v, 1 / 2.4) - 0.055;
}

function clamp01(v: number): number {
  if (v < 0) return 0;
  if (v > 1) return 1;
  return v;
}

function hslToRgb(h: number, s: number, l: number): RGB {
  s /= 100;
  l /= 100;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = (h % 360) / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r1 = 0, g1 = 0, b1 = 0;
  if (hp < 1) [r1, g1, b1] = [c, x, 0];
  else if (hp < 2) [r1, g1, b1] = [x, c, 0];
  else if (hp < 3) [r1, g1, b1] = [0, c, x];
  else if (hp < 4) [r1, g1, b1] = [0, x, c];
  else if (hp < 5) [r1, g1, b1] = [x, 0, c];
  else [r1, g1, b1] = [c, 0, x];
  const m = l - c / 2;
  return { r: r1 + m, g: g1 + m, b: b1 + m };
}

// Validates an identifier-like string before interpolating it into generated
// Figma Plugin code. Token names, component names, page categories, and
// variant values all flow into JS string literals via JSON.stringify (which
// escapes quotes/backslashes correctly), but we still want a hard guard
// against newlines, control chars, and JS comment markers in case future
// edits embed values without JSON.stringify wrapping. Throws on violation
// so the failure surfaces at plan-generation time instead of in Figma.
function sanitizeIdentifier(value: string, kind: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`storysync push: ${kind} is empty`);
  }
  if (value.length > 200) {
    throw new Error(`storysync push: ${kind} too long (>200 chars): ${value.slice(0, 80)}…`);
  }
  // Allow letters, digits, common separators (space, dash, underscore,
  // forward slash, dot). Reject anything that could break out of a string
  // or comment context.
  if (!/^[A-Za-z0-9 _\-/.]+$/.test(value)) {
    throw new Error(
      `storysync push: ${kind} contains unsupported characters (${JSON.stringify(value)}). ` +
      `Only letters, digits, space, and ._-/ are allowed.`,
    );
  }
  return value;
}

function rgbToJsLiteral(rgb: RGB): string {
  const fmt = (n: number) => Number(n.toFixed(4));
  if (rgb.a != null && rgb.a < 1) {
    return `{ r: ${fmt(rgb.r)}, g: ${fmt(rgb.g)}, b: ${fmt(rgb.b)}, a: ${fmt(rgb.a)} }`;
  }
  return `{ r: ${fmt(rgb.r)}, g: ${fmt(rgb.g)}, b: ${fmt(rgb.b)} }`;
}

function parsePadding(value: string | null | undefined): { t: number; r: number; b: number; l: number } {
  if (!value) return { t: 0, r: 0, b: 0, l: 0 };
  const parts = value.split(/\s+/).map((p) => parsePxNumber(p) ?? 0);
  if (parts.length === 1) return { t: parts[0], r: parts[0], b: parts[0], l: parts[0] };
  if (parts.length === 2) return { t: parts[0], r: parts[1], b: parts[0], l: parts[1] };
  if (parts.length === 3) return { t: parts[0], r: parts[1], b: parts[2], l: parts[1] };
  return { t: parts[0], r: parts[1], b: parts[2], l: parts[3] };
}

function parsePxNumber(value: string | null | undefined): number | null {
  if (value == null) return null;
  const n = parseFloat(value);
  return isNaN(n) ? null : n;
}

function lengthToPx(value: string): number | null {
  const t = value.trim();
  const m = t.match(/^(-?\d+(?:\.\d+)?)\s*(px|rem|em)?$/);
  if (!m) return null;
  const n = parseFloat(m[1]);
  if (isNaN(n)) return null;
  if (m[2] === "rem" || m[2] === "em") return Math.round(n * 16 * 100) / 100;
  return n;
}

function extractBorderWidth(border: string | null | undefined): number | null {
  if (!border) return null;
  const m = border.match(/^(\d+(?:\.\d+)?)px/);
  return m ? parseFloat(m[1]) : null;
}

function extractBorderColor(border: string | null | undefined): string | null {
  if (!border) return null;
  const m = border.match(/(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)|hsla?\([^)]+\))$/);
  return m ? m[1] : null;
}

function parseShadow(value: string | null | undefined): object | null {
  if (!value) return null;
  // Best-effort: match "<X>px <Y>px <BLUR>px <SPREAD?>px <COLOR>". Tailwind
  // shadows often have multiple layers; we take the first.
  const m = value.match(/(-?\d+(?:\.\d+)?)px\s+(-?\d+(?:\.\d+)?)px\s+(\d+(?:\.\d+)?)px(?:\s+(-?\d+(?:\.\d+)?)px)?\s+(.+?)(?:,|$)/);
  if (!m) return null;
  const color = parseColorToRgb(m[5].trim()) ?? { r: 0, g: 0, b: 0, a: 0.1 };
  return {
    type: "DROP_SHADOW",
    offset: { x: parseFloat(m[1]), y: parseFloat(m[2]) },
    radius: parseFloat(m[3]),
    spread: m[4] != null ? parseFloat(m[4]) : 0,
    color: { r: color.r, g: color.g, b: color.b, a: color.a ?? 1 },
    blendMode: "NORMAL",
    visible: true,
  };
}

function pickFontStyle(styling: ResolvedStyling): string {
  const w = parseFloat(styling.fontWeight ?? "400");
  if (isNaN(w)) return "Regular";
  if (w >= 600) return "Semi Bold";
  if (w >= 500) return "Medium";
  return "Regular";
}

function figmaAlignment(value: string): string {
  // Figma counterAxisAlignItems: MIN | CENTER | MAX | BASELINE
  switch (value) {
    case "start": return "MIN";
    case "end": return "MAX";
    case "center": return "CENTER";
    case "baseline": return "BASELINE";
    default: return "CENTER";
  }
}

function figmaJustify(value: string): string | null {
  // Figma primaryAxisAlignItems only supports MIN | CENTER | MAX | SPACE_BETWEEN.
  // Tailwind's `justify-around`/`justify-evenly` have no Figma equivalent;
  // returning null here causes the caller to skip the assignment and surface
  // a warning rather than silently coercing the layout to start-aligned.
  switch (value) {
    case "start": return "MIN";
    case "end": return "MAX";
    case "center": return "CENTER";
    case "between": return "SPACE_BETWEEN";
    default: return null;
  }
}

// --- Plan orchestration ---

export interface PlanInput {
  fileKey: string;
  collections: TokenCollection[];
  components: ComponentInput[];
}

export function generatePushPlan(input: PlanInput): PushPlan {
  const scripts: PushScript[] = [];
  const warnings: string[] = [];

  // Walk every component's bindings to collect Tailwind-palette colors
  // referenced from any styling field (fill, text, borderColor, etc.).
  // These get added to the Colors collection so components — particularly
  // Catalyst's, which hardcode `var(--color-red-600)` etc. — can actually
  // bind their fills to a Figma variable instead of writing a literal hex.
  const paletteColors = collectPaletteColors(input.components);
  const augmentedCollections = mergePaletteIntoColors(input.collections, paletteColors);

  // Components grouped by page for the Cover summary.
  const componentsWithStyling = input.components.filter((c) => c.styling);
  const pageSummary = computePageSummary(componentsWithStyling);
  const variableTotal = augmentedCollections.reduce((acc, c) => acc + c.tokens.length, 0);

  // Setup script first: Cover page, page cleanup.
  scripts.push(generateSetupScript({
    pageSummary,
    componentTotal: componentsWithStyling.length,
    variableTotal,
  }));

  if (augmentedCollections.length) {
    scripts.push(generateVariablesScript(augmentedCollections));
  } else {
    warnings.push("No token collections to create.");
  }

  for (const c of input.components) {
    if (!c.styling) {
      warnings.push(`Skipped ${c.name}: no styling spec available (component source not found by inspect).`);
      continue;
    }
    scripts.push(generateComponentScript(c));
  }

  return { fileKey: input.fileKey, scripts, warnings };
}

function computePageSummary(components: ComponentInput[]): { name: string; componentCount: number }[] {
  const counts = new Map<string, number>();
  for (const c of components) {
    const page = c.category || "Components";
    counts.set(page, (counts.get(page) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, componentCount]) => ({ name, componentCount }));
}

// Returns the set of Tailwind-palette names referenced as bindings across
// every component's base + per-variant styling.
function collectPaletteColors(components: ComponentInput[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const c of components) {
    if (!c.styling) continue;
    const addFromBindings = (bindings: import("./inspect.js").Bindings, styling: ResolvedStyling) => {
      for (const [field, b] of Object.entries(bindings)) {
        if (!b || b.source !== "palette" || b.collection !== "colors") continue;
        // The literal value lives in the matching styling field; use that
        // when emitting the variable's value.
        const literal = (styling as Record<string, unknown>)[field];
        if (typeof literal === "string") out.set(b.token, literal);
      }
    };
    addFromBindings(c.styling.baseBindings, c.styling.base);
    for (const variant of c.styling.variants) {
      for (const [valueName, b] of Object.entries(variant.bindings)) {
        addFromBindings(b, variant.values[valueName] ?? {});
      }
    }
  }
  return out;
}

// Merge palette colors into the user's existing colors collection (or
// create one if absent). Existing project tokens win — we never overwrite
// a user's `primary: #abc123` with the bundled `primary: #def`.
function mergePaletteIntoColors(
  collections: TokenCollection[],
  paletteColors: Map<string, string>,
): TokenCollection[] {
  if (paletteColors.size === 0) return collections;

  const existing = collections.find((c) => c.category === "colors");
  const existingNames = new Set(existing?.tokens.map((t) => t.name) ?? []);
  const additions: { name: string; value: string }[] = [];
  for (const [name, value] of paletteColors) {
    if (!existingNames.has(name)) additions.push({ name, value });
  }
  if (!additions.length) return collections;

  if (existing) {
    return collections.map((c) =>
      c === existing ? { ...c, tokens: [...c.tokens, ...additions] } : c,
    );
  }
  return [...collections, { category: "colors", tokens: additions }];
}
