// Generates Figma Plugin API JavaScript that can be sent verbatim to
// `use_figma`. The whole point is to remove agent discretion: instead of
// asking the agent to translate inspect output into use_figma calls (which
// it keeps screwing up by skipping bindings), we emit the exact plugin code
// here and the agent's only job is to pipe each script through use_figma.
//
// The scripts are designed to be idempotent (re-runs don't duplicate) and
// self-resolving (each component script looks up variables by name at
// runtime, so they can reference variables a previous script created
// without us having to thread IDs through the JSON output).

import type { TokenCollection, TokenValue } from "./tokens.js";
import type { FigmaVariantProperty } from "./mapper.js";
import type { InspectionResult, ResolvedStyling, Bindings } from "./inspect.js";

export interface PushScript {
  label: string;
  code: string;
}

export interface PushPlan {
  fileKey: string;
  scripts: PushScript[];
  warnings: string[];
}

// Figma color: { r, g, b } in 0..1, plus optional `a`.
interface RGB {
  r: number;
  g: number;
  b: number;
  a?: number;
}

// --- Variable-collection script ---

export function generateVariablesScript(collections: TokenCollection[]): PushScript {
  const lines: string[] = [];
  lines.push("// Auto-generated by storysync push — creates/updates token variable collections.");
  lines.push("// Idempotent: re-running keeps existing variables and updates their values.");
  lines.push("(async () => {");
  lines.push("  const upsertCollection = (name) => {");
  lines.push("    let c = figma.variables.getLocalVariableCollections().find((c) => c.name === name);");
  lines.push("    if (!c) c = figma.variables.createVariableCollection(name);");
  lines.push("    return c;");
  lines.push("  };");
  lines.push("  const upsertVariable = (collection, name, type) => {");
  lines.push("    const existing = figma.variables");
  lines.push("      .getLocalVariables()");
  lines.push("      .find((v) => v.variableCollectionId === collection.id && v.name === name);");
  lines.push("    return existing || figma.variables.createVariable(name, collection, type);");
  lines.push("  };");
  lines.push("");

  let total = 0;
  for (const coll of collections) {
    const meta = COLLECTION_META[coll.category];
    if (!meta) continue;

    const safeName = meta.name;
    const figmaType = meta.figmaType;
    const scopes = JSON.stringify(meta.scopes);

    lines.push(`  // ${safeName} (${coll.tokens.length} variables)`);
    lines.push(`  {`);
    lines.push(`    const coll = upsertCollection(${JSON.stringify(safeName)});`);
    lines.push(`    const mode = coll.modes[0].modeId;`);

    for (const t of coll.tokens) {
      const value = serializeTokenValue(coll.category, t);
      if (value == null) continue;
      lines.push(`    {`);
      lines.push(`      const v = upsertVariable(coll, ${JSON.stringify(t.name)}, ${JSON.stringify(figmaType)});`);
      lines.push(`      v.setValueForMode(mode, ${value});`);
      lines.push(`      v.scopes = ${scopes};`);
      lines.push(`    }`);
      total++;
    }
    lines.push(`  }`);
    lines.push("");
  }

  lines.push(`  console.log("storysync: upserted " + ${total} + " variables across ${collections.length} collections");`);
  lines.push("})();");

  return {
    label: `Create or update ${total} variables across ${collections.length} collections`,
    code: lines.join("\n"),
  };
}

interface CollectionMeta {
  name: string;
  figmaType: "COLOR" | "FLOAT" | "STRING";
  scopes: string[];
}

const COLLECTION_META: Record<string, CollectionMeta> = {
  colors: { name: "Colors", figmaType: "COLOR", scopes: ["ALL_FILLS", "STROKE_COLOR"] },
  spacing: { name: "Spacing", figmaType: "FLOAT", scopes: ["GAP", "WIDTH_HEIGHT"] },
  radius: { name: "Radius", figmaType: "FLOAT", scopes: ["CORNER_RADIUS"] },
  shadows: { name: "Shadows", figmaType: "STRING", scopes: ["ALL_SCOPES"] },
  typography: { name: "Typography", figmaType: "FLOAT", scopes: ["FONT_SIZE"] },
};

// Returns a JS literal expression for the value, or null when not serializable.
function serializeTokenValue(category: string, token: TokenValue): string | null {
  if (category === "colors") {
    const rgb = parseColorToRgb(token.value);
    if (!rgb) return null;
    return rgbToJsLiteral(rgb);
  }
  // Numeric categories: spacing / radius / typography.
  if (category === "spacing" || category === "radius" || category === "typography") {
    const px = lengthToPx(token.value);
    if (px == null) return null;
    return String(px);
  }
  // Shadows are stored as STRING for now (no first-class effect-style binding).
  if (category === "shadows") return JSON.stringify(token.value);
  return null;
}

// --- Component-set script ---

export interface ComponentInput {
  name: string;
  category?: string;
  variantProperties: FigmaVariantProperty[];
  styling: InspectionResult;
}

export function generateComponentScript(input: ComponentInput): PushScript {
  const pageName = sanitizeIdentifier(input.category || "Components", "category");
  const compName = sanitizeIdentifier(input.name, "component name");
  for (const p of input.variantProperties) {
    sanitizeIdentifier(p.name, "variant property name");
    for (const v of p.values) sanitizeIdentifier(v, "variant value");
  }
  const matrix = enumerateVariantMatrix(input.variantProperties);

  const lines: string[] = [];
  lines.push(`// Auto-generated by storysync push — ${compName} (${matrix.length} variants)`);
  lines.push(`(async () => {`);
  lines.push(`  // 1) Page lookup/create`);
  lines.push(`  let page = figma.root.children.find((p) => p.name === ${JSON.stringify(pageName)});`);
  lines.push(`  if (!page) { page = figma.createPage(); page.name = ${JSON.stringify(pageName)}; }`);
  lines.push(`  await figma.setCurrentPageAsync(page);`);
  lines.push("");

  lines.push(`  // 2) Variable lookup helper — resolves bindings at runtime`);
  lines.push(`  const lookupVar = (collName, varName) => {`);
  lines.push(`    const coll = figma.variables.getLocalVariableCollections().find((c) => c.name === collName);`);
  lines.push(`    if (!coll) return null;`);
  lines.push(`    return figma.variables.getLocalVariables().find((v) => v.variableCollectionId === coll.id && v.name === varName) || null;`);
  lines.push(`  };`);
  lines.push("");

  lines.push(`  // 3) Font preload (the only font we use for V1 labels)`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Regular" });`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Medium" });`);
  lines.push(`  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });`);
  lines.push("");

  lines.push(`  // 4) Remove any prior component set with the same name on this page so re-runs don't pile up`);
  lines.push(`  for (const child of page.children) {`);
  lines.push(`    if (child.type === "COMPONENT_SET" && child.name === ${JSON.stringify(compName)}) child.remove();`);
  lines.push(`  }`);
  lines.push("");

  lines.push(`  const variants = [];`);
  for (const combo of matrix) {
    const variantName = formatVariantName(combo);
    const styling = mergeStylingForCombo(input.styling, combo);
    const bindings = mergeBindingsForCombo(input.styling, combo);
    lines.push(`  variants.push((function () {`);
    lines.push(`    const f = figma.createFrame();`);
    lines.push(`    f.name = ${JSON.stringify(variantName)};`);
    lines.push(...emitFrameStyling(styling, bindings).map((l) => `    ${l}`));
    lines.push(`    // Label so the variant is visually identifiable; agents can replace later.`);
    lines.push(`    const label = figma.createText();`);
    lines.push(`    label.fontName = { family: "Inter", style: ${JSON.stringify(pickFontStyle(styling))} };`);
    lines.push(`    label.fontSize = ${JSON.stringify(parsePxNumber(styling.fontSize) ?? 14)};`);
    lines.push(`    label.characters = ${JSON.stringify(compName)};`);
    if (styling.text) {
      const labelFill = paintFromStyling(styling.text);
      if (labelFill) lines.push(`    label.fills = [${labelFill}];`);
    }
    if (bindings.text) {
      lines.push(`    { const v = lookupVar(${JSON.stringify(COLLECTION_META[bindings.text.collection].name)}, ${JSON.stringify(bindings.text.token)}); if (v) label.setBoundVariable("fills", v); }`);
    }
    lines.push(`    f.appendChild(label);`);
    lines.push(`    return f;`);
    lines.push(`  })());`);
  }
  lines.push("");
  if (matrix.length > 1) {
    lines.push(`  const set = figma.combineAsVariants(variants, page);`);
    lines.push(`  set.name = ${JSON.stringify(compName)};`);
  } else {
    // Single-variant path: convert the lone frame into a Component while
    // preserving every property emitFrameStyling already set on it (auto-
    // layout, padding, fills, radius, opacity, effects, bindings).
    lines.push(`  const single = figma.createComponent();`);
    lines.push(`  single.name = ${JSON.stringify(compName)};`);
    lines.push(`  const src = variants[0];`);
    lines.push(`  // Mirror styling from the staged frame to the component.`);
    lines.push(`  single.layoutMode = src.layoutMode;`);
    lines.push(`  single.primaryAxisSizingMode = src.primaryAxisSizingMode;`);
    lines.push(`  single.counterAxisSizingMode = src.counterAxisSizingMode;`);
    lines.push(`  single.paddingTop = src.paddingTop; single.paddingRight = src.paddingRight; single.paddingBottom = src.paddingBottom; single.paddingLeft = src.paddingLeft;`);
    lines.push(`  single.itemSpacing = src.itemSpacing;`);
    lines.push(`  single.counterAxisAlignItems = src.counterAxisAlignItems;`);
    lines.push(`  single.primaryAxisAlignItems = src.primaryAxisAlignItems;`);
    lines.push(`  single.cornerRadius = src.cornerRadius;`);
    lines.push(`  single.fills = src.fills;`);
    lines.push(`  single.strokes = src.strokes;`);
    lines.push(`  single.strokeWeight = src.strokeWeight;`);
    lines.push(`  single.dashPattern = src.dashPattern;`);
    lines.push(`  single.effects = src.effects;`);
    lines.push(`  single.opacity = src.opacity;`);
    lines.push(`  // Preserve any variable bindings on the frame.`);
    lines.push(`  if (src.boundVariables) {`);
    lines.push(`    for (const [field, binding] of Object.entries(src.boundVariables)) {`);
    lines.push(`      const v = figma.variables.getVariableById(binding.id);`);
    lines.push(`      if (v) single.setBoundVariable(field, v);`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`  for (const child of [...src.children]) single.appendChild(child);`);
    lines.push(`  src.remove();`);
    lines.push(`  page.appendChild(single);`);
  }
  lines.push(`  console.log("storysync: created ${compName} with ${matrix.length} variants on page ${pageName}");`);
  lines.push(`})();`);

  return {
    label: `Create ${compName} (${matrix.length} variants) on ${pageName}`,
    code: lines.join("\n"),
  };
}

// Cartesian product of variant properties. Each entry is a map of
// propName → value. For BOOLEAN, values are the strings "true"/"false".
function enumerateVariantMatrix(props: FigmaVariantProperty[]): Record<string, string>[] {
  if (!props.length) return [{}];
  let combos: Record<string, string>[] = [{}];
  for (const p of props) {
    const next: Record<string, string>[] = [];
    for (const existing of combos) {
      for (const v of p.values) next.push({ ...existing, [p.name]: v });
    }
    combos = next;
  }
  return combos;
}

function formatVariantName(combo: Record<string, string>): string {
  const parts = Object.entries(combo).map(([k, v]) => `${k}=${v}`);
  return parts.length ? parts.join(", ") : "Default";
}

// For a given combo, walk the inspect result and merge base + the matching
// variant value's styling. Later values win over earlier so a variant value
// can override a base property.
function mergeStylingForCombo(spec: InspectionResult, combo: Record<string, string>): ResolvedStyling {
  const out: ResolvedStyling = { ...spec.base };
  for (const variant of spec.variants) {
    const value = combo[variant.name];
    if (value == null) continue;
    const v = variant.values[value];
    if (!v) continue;
    Object.assign(out, v);
  }
  return out;
}

function mergeBindingsForCombo(spec: InspectionResult, combo: Record<string, string>): Bindings {
  const out: Bindings = { ...spec.baseBindings };
  for (const variant of spec.variants) {
    const value = combo[variant.name];
    if (value == null) continue;
    const b = variant.bindings[value];
    if (!b) continue;
    Object.assign(out, b);
  }
  return out;
}

// Emits the JS lines that style a frame `f` from the given styling +
// bindings. Auto-layout is enabled by default since most components are
// flex/inline-flex; absolute positioning is out of scope for V1.
function emitFrameStyling(styling: ResolvedStyling, bindings: Bindings): string[] {
  const out: string[] = [];
  // Auto-layout
  out.push(`f.layoutMode = ${JSON.stringify(styling.layout === "column" ? "VERTICAL" : "HORIZONTAL")};`);
  out.push(`f.primaryAxisSizingMode = "AUTO";`);
  out.push(`f.counterAxisSizingMode = "AUTO";`);

  // Padding
  const padding = parsePadding(styling.padding);
  out.push(`f.paddingTop = ${padding.t}; f.paddingRight = ${padding.r}; f.paddingBottom = ${padding.b}; f.paddingLeft = ${padding.l};`);

  // Gap (item spacing). Bind if available.
  const gapPx = parsePxNumber(styling.gap) ?? 0;
  out.push(`f.itemSpacing = ${gapPx};`);
  if (bindings.gap) {
    out.push(`{ const v = lookupVar(${JSON.stringify(COLLECTION_META[bindings.gap.collection].name)}, ${JSON.stringify(bindings.gap.token)}); if (v) f.setBoundVariable("itemSpacing", v); }`);
  }

  // Alignment helpers (best-effort mapping from Tailwind to Figma)
  if (styling.alignItems) out.push(`f.counterAxisAlignItems = ${JSON.stringify(figmaAlignment(styling.alignItems))};`);
  if (styling.justifyContent) out.push(`f.primaryAxisAlignItems = ${JSON.stringify(figmaJustify(styling.justifyContent))};`);

  // Corner radius
  const radius = parsePxNumber(styling.borderRadius);
  if (radius != null) {
    out.push(`f.cornerRadius = ${radius};`);
    if (bindings.borderRadius) {
      out.push(`{ const v = lookupVar(${JSON.stringify(COLLECTION_META[bindings.borderRadius.collection].name)}, ${JSON.stringify(bindings.borderRadius.token)}); if (v) f.setBoundVariable("topLeftRadius", v); f.setBoundVariable && f.setBoundVariable("topRightRadius", v); f.setBoundVariable && f.setBoundVariable("bottomLeftRadius", v); f.setBoundVariable && f.setBoundVariable("bottomRightRadius", v); }`);
    }
  }

  // Fill
  const fillPaint = paintFromStyling(styling.fill);
  if (fillPaint) {
    out.push(`f.fills = [${fillPaint}];`);
  } else {
    out.push(`f.fills = [];`);
  }
  if (bindings.fill) {
    out.push(`{ const v = lookupVar(${JSON.stringify(COLLECTION_META[bindings.fill.collection].name)}, ${JSON.stringify(bindings.fill.token)}); if (v) f.setBoundVariable("fills", v); }`);
  }

  // Stroke (border)
  if (styling.borderColor || styling.border) {
    const stroke = paintFromStyling(styling.borderColor ?? extractBorderColor(styling.border));
    if (stroke) {
      out.push(`f.strokes = [${stroke}];`);
      out.push(`f.strokeWeight = ${extractBorderWidth(styling.border) ?? 1};`);
      if (styling.borderStyle && styling.borderStyle !== "solid") {
        const dashes = styling.borderStyle === "dashed" ? [6, 4] : styling.borderStyle === "dotted" ? [2, 2] : [];
        if (dashes.length) out.push(`f.dashPattern = ${JSON.stringify(dashes)};`);
      }
    }
  }
  if (bindings.borderColor) {
    out.push(`{ const v = lookupVar(${JSON.stringify(COLLECTION_META[bindings.borderColor.collection].name)}, ${JSON.stringify(bindings.borderColor.token)}); if (v) f.setBoundVariable("strokes", v); }`);
  }

  // Effects (shadow). We only support DROP_SHADOW with a heuristic parse.
  const shadow = parseShadow(styling.shadow);
  if (shadow) {
    out.push(`f.effects = [${JSON.stringify(shadow)}];`);
  }

  // Opacity
  if (styling.opacity != null) {
    const o = parseFloat(styling.opacity);
    if (!isNaN(o)) out.push(`f.opacity = ${o};`);
  }

  return out;
}

// --- Color / value parsers ---

export function parseColorToRgb(value: string): RGB | null {
  const v = value.trim();
  // Hex
  let m = v.match(/^#([0-9a-fA-F]{3,8})$/);
  if (m) {
    let hex = m[1];
    if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
    if (hex.length === 6 || hex.length === 8) {
      const r = parseInt(hex.slice(0, 2), 16) / 255;
      const g = parseInt(hex.slice(2, 4), 16) / 255;
      const b = parseInt(hex.slice(4, 6), 16) / 255;
      const a = hex.length === 8 ? parseInt(hex.slice(6, 8), 16) / 255 : undefined;
      return a != null ? { r, g, b, a } : { r, g, b };
    }
  }
  // rgb / rgba — accepts both Tailwind v3 space-separated form
  // (`rgb(255 0 0 / 0.5)`) and the legacy comma-separated form. Alpha may
  // be a fraction (`0.5`) or a percent (`50%`).
  m = v.match(/^rgba?\(\s*(\d+(?:\.\d+)?)\s*[,\s]\s*(\d+(?:\.\d+)?)\s*[,\s]\s*(\d+(?:\.\d+)?)\s*(?:[,\/]\s*(\d+(?:\.\d+)?%?))?\s*\)$/i);
  if (m) {
    const result: RGB = {
      r: parseFloat(m[1]) / 255,
      g: parseFloat(m[2]) / 255,
      b: parseFloat(m[3]) / 255,
    };
    if (m[4] != null) {
      const aStr = m[4];
      const a = aStr.endsWith("%") ? parseFloat(aStr) / 100 : parseFloat(aStr);
      if (!isNaN(a)) result.a = a;
    }
    return result;
  }
  // hsl / hsla — including the bare-component form `224 71% 4%` shadcn uses.
  m = v.match(/^hsla?\(\s*(\d+(?:\.\d+)?)(?:deg)?[,\s]+(\d+(?:\.\d+)?)%[,\s]+(\d+(?:\.\d+)?)%(?:[\s,/]+(\d*\.?\d+%?))?\s*\)$/i)
    ?? v.match(/^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%\s+(\d+(?:\.\d+)?)%$/);
  if (m) {
    const rgb = hslToRgb(parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3]));
    if (m[4] != null) {
      const aStr = m[4];
      const a = aStr.endsWith("%") ? parseFloat(aStr) / 100 : parseFloat(aStr);
      if (!isNaN(a)) return { ...rgb, a };
    }
    return rgb;
  }
  // Named special cases used by tokens
  if (v === "transparent") return { r: 0, g: 0, b: 0, a: 0 };
  if (v === "white") return { r: 1, g: 1, b: 1 };
  if (v === "black") return { r: 0, g: 0, b: 0 };
  return null;
}

function hslToRgb(h: number, s: number, l: number): RGB {
  s /= 100;
  l /= 100;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = (h % 360) / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r1 = 0, g1 = 0, b1 = 0;
  if (hp < 1) [r1, g1, b1] = [c, x, 0];
  else if (hp < 2) [r1, g1, b1] = [x, c, 0];
  else if (hp < 3) [r1, g1, b1] = [0, c, x];
  else if (hp < 4) [r1, g1, b1] = [0, x, c];
  else if (hp < 5) [r1, g1, b1] = [x, 0, c];
  else [r1, g1, b1] = [c, 0, x];
  const m = l - c / 2;
  return { r: r1 + m, g: g1 + m, b: b1 + m };
}

// Validates an identifier-like string before interpolating it into generated
// Figma Plugin code. Token names, component names, page categories, and
// variant values all flow into JS string literals via JSON.stringify (which
// escapes quotes/backslashes correctly), but we still want a hard guard
// against newlines, control chars, and JS comment markers in case future
// edits embed values without JSON.stringify wrapping. Throws on violation
// so the failure surfaces at plan-generation time instead of in Figma.
function sanitizeIdentifier(value: string, kind: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`storysync push: ${kind} is empty`);
  }
  if (value.length > 200) {
    throw new Error(`storysync push: ${kind} too long (>200 chars): ${value.slice(0, 80)}…`);
  }
  // Allow letters, digits, common separators (space, dash, underscore,
  // forward slash, dot). Reject anything that could break out of a string
  // or comment context.
  if (!/^[A-Za-z0-9 _\-/.]+$/.test(value)) {
    throw new Error(
      `storysync push: ${kind} contains unsupported characters (${JSON.stringify(value)}). ` +
      `Only letters, digits, space, and ._-/ are allowed.`,
    );
  }
  return value;
}

function rgbToJsLiteral(rgb: RGB): string {
  const fmt = (n: number) => Number(n.toFixed(4));
  if (rgb.a != null && rgb.a < 1) {
    return `{ r: ${fmt(rgb.r)}, g: ${fmt(rgb.g)}, b: ${fmt(rgb.b)}, a: ${fmt(rgb.a)} }`;
  }
  return `{ r: ${fmt(rgb.r)}, g: ${fmt(rgb.g)}, b: ${fmt(rgb.b)} }`;
}

function paintFromStyling(value: string | null | undefined): string | null {
  if (!value) return null;
  if (value === "transparent") return null;
  const rgb = parseColorToRgb(value);
  if (!rgb) return null;
  if (rgb.a != null && rgb.a < 1) {
    return `{ type: "SOLID", color: { r: ${rgb.r.toFixed(4)}, g: ${rgb.g.toFixed(4)}, b: ${rgb.b.toFixed(4)} }, opacity: ${rgb.a.toFixed(4)} }`;
  }
  return `{ type: "SOLID", color: { r: ${rgb.r.toFixed(4)}, g: ${rgb.g.toFixed(4)}, b: ${rgb.b.toFixed(4)} } }`;
}

function parsePadding(value: string | null | undefined): { t: number; r: number; b: number; l: number } {
  if (!value) return { t: 0, r: 0, b: 0, l: 0 };
  const parts = value.split(/\s+/).map((p) => parsePxNumber(p) ?? 0);
  if (parts.length === 1) return { t: parts[0], r: parts[0], b: parts[0], l: parts[0] };
  if (parts.length === 2) return { t: parts[0], r: parts[1], b: parts[0], l: parts[1] };
  if (parts.length === 3) return { t: parts[0], r: parts[1], b: parts[2], l: parts[1] };
  return { t: parts[0], r: parts[1], b: parts[2], l: parts[3] };
}

function parsePxNumber(value: string | null | undefined): number | null {
  if (value == null) return null;
  const n = parseFloat(value);
  return isNaN(n) ? null : n;
}

function lengthToPx(value: string): number | null {
  const t = value.trim();
  const m = t.match(/^(-?\d+(?:\.\d+)?)\s*(px|rem|em)?$/);
  if (!m) return null;
  const n = parseFloat(m[1]);
  if (isNaN(n)) return null;
  if (m[2] === "rem" || m[2] === "em") return Math.round(n * 16 * 100) / 100;
  return n;
}

function extractBorderWidth(border: string | null | undefined): number | null {
  if (!border) return null;
  const m = border.match(/^(\d+(?:\.\d+)?)px/);
  return m ? parseFloat(m[1]) : null;
}

function extractBorderColor(border: string | null | undefined): string | null {
  if (!border) return null;
  const m = border.match(/(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)|hsla?\([^)]+\))$/);
  return m ? m[1] : null;
}

function parseShadow(value: string | null | undefined): object | null {
  if (!value) return null;
  // Best-effort: match "<X>px <Y>px <BLUR>px <SPREAD?>px <COLOR>". Tailwind
  // shadows often have multiple layers; we take the first.
  const m = value.match(/(-?\d+(?:\.\d+)?)px\s+(-?\d+(?:\.\d+)?)px\s+(\d+(?:\.\d+)?)px(?:\s+(-?\d+(?:\.\d+)?)px)?\s+(.+?)(?:,|$)/);
  if (!m) return null;
  const color = parseColorToRgb(m[5].trim()) ?? { r: 0, g: 0, b: 0, a: 0.1 };
  return {
    type: "DROP_SHADOW",
    offset: { x: parseFloat(m[1]), y: parseFloat(m[2]) },
    radius: parseFloat(m[3]),
    spread: m[4] != null ? parseFloat(m[4]) : 0,
    color: { r: color.r, g: color.g, b: color.b, a: color.a ?? 1 },
    blendMode: "NORMAL",
    visible: true,
  };
}

function pickFontStyle(styling: ResolvedStyling): string {
  const w = parseFloat(styling.fontWeight ?? "400");
  if (isNaN(w)) return "Regular";
  if (w >= 600) return "Semi Bold";
  if (w >= 500) return "Medium";
  return "Regular";
}

function figmaAlignment(value: string): string {
  // Figma counterAxisAlignItems: MIN | CENTER | MAX | BASELINE
  switch (value) {
    case "start": return "MIN";
    case "end": return "MAX";
    case "center": return "CENTER";
    case "baseline": return "BASELINE";
    default: return "CENTER";
  }
}

function figmaJustify(value: string): string {
  // Figma primaryAxisAlignItems: MIN | CENTER | MAX | SPACE_BETWEEN
  switch (value) {
    case "start": return "MIN";
    case "end": return "MAX";
    case "center": return "CENTER";
    case "between": return "SPACE_BETWEEN";
    default: return "MIN";
  }
}

// --- Plan orchestration ---

export interface PlanInput {
  fileKey: string;
  collections: TokenCollection[];
  components: ComponentInput[];
}

export function generatePushPlan(input: PlanInput): PushPlan {
  const scripts: PushScript[] = [];
  const warnings: string[] = [];

  if (input.collections.length) {
    scripts.push(generateVariablesScript(input.collections));
  } else {
    warnings.push("No token collections to create.");
  }

  for (const c of input.components) {
    if (!c.styling) {
      warnings.push(`Skipped ${c.name}: no styling spec available (component source not found by inspect).`);
      continue;
    }
    scripts.push(generateComponentScript(c));
  }

  return { fileKey: input.fileKey, scripts, warnings };
}
